# Generated by Django 5.2.3 on 2025-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='colors',
            field=models.JSONField(default=['none', 'none', 'none', 'none', 'none']),
        ),
    ]
