# Generated by Django 5.2.3 on 2025-07-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_suggestion_guess_colors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guess',
        ),
    ]
